apiVersion: '2021-03-01'
location: westeu
name: myContainerGroup
properties:
  containers:
  - name: myPythonApp
    properties:
      image: yourdockerhubaccount/your-python-app:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      environmentVariables:
      - name: MONGO_URI
        value: "mongodb://<username>:<password>@myMongoDB.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb"
      ports:
      - port: 80
        protocol: TCP
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
    - port: 80
      protocol: TCP
tags: {}
type: Microsoft.ContainerInstance/containerGroups

